#!/usr/bin/env bash
# create-bump-pr.sh — commit package-bump changes and open a PR via gh.
#
# Inputs (env):
#   GH_TOKEN            — gh CLI token (required)
#   MSD_BASE_BRANCH     — target branch for the PR (required)
#   MSD_BRANCH_PREFIX   — prefix for the working branch name (required)
#   MSD_COMMIT_PREFIX   — prefix for commit message / PR title (required)
#   MSD_PACKAGE_ID      — package name (required)
#   MSD_CURRENT_VERSION — version before bump (required)
#   MSD_LATEST_VERSION  — target version (required)
#   MSD_PR_LABELS       — comma-separated labels to apply (optional)
#   MSD_FILES_CHANGED   — newline-separated paths to stage (required)
#
# Skips gracefully when the PR branch already exists on the remote
# (prior/concurrent runs are treated as idempotent).
set -euo pipefail

base="${MSD_BASE_BRANCH:?MSD_BASE_BRANCH required}"
branch_prefix="${MSD_BRANCH_PREFIX:?MSD_BRANCH_PREFIX required}"
commit_prefix="${MSD_COMMIT_PREFIX:?MSD_COMMIT_PREFIX required}"
pkg="${MSD_PACKAGE_ID:?MSD_PACKAGE_ID required}"
current="${MSD_CURRENT_VERSION:?MSD_CURRENT_VERSION required}"
latest="${MSD_LATEST_VERSION:?MSD_LATEST_VERSION required}"
labels="${MSD_PR_LABELS:-}"
files_changed="${MSD_FILES_CHANGED:-}"

git config user.name  'github-actions[bot]'
git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

branch="${branch_prefix}-${pkg}-${latest}"

if git ls-remote --exit-code --heads origin "$branch" >/dev/null 2>&1; then
  echo "Branch $branch already exists on remote — skipping."
  exit 0
fi

git checkout -b "$branch"

while IFS= read -r f; do
  [[ -n "$f" ]] && git add -- "$f"
done <<< "$files_changed"

msg="${commit_prefix} ${pkg} from ${current} to ${latest}"
git commit -m "$msg"
git push -u origin "$branch"

body=$(cat <<EOF
Bumps \`${pkg}\` from \`${current}\` to \`${latest}\`.

Changed files:
\`\`\`
${files_changed}
\`\`\`

Auto-generated by [\`modsharp-publish-action/bump-nuget.yml\`](https://github.com/fltuna/modsharp-publish-action/blob/v1/.github/workflows/bump-nuget.yml).
EOF
)

label_args=()
if [[ -n "${labels}" ]]; then
  IFS=',' read -r -a arr <<< "${labels}"
  for l in "${arr[@]}"; do
    l_trimmed="$(echo -n "$l" | xargs)"
    [[ -n "$l_trimmed" ]] && label_args+=(--label "$l_trimmed")
  done
fi

gh pr create \
  --base "${base}" \
  --head "${branch}" \
  --title "${msg}" \
  --body "${body}" \
  "${label_args[@]}"
